// export const SAVE_EX_REQUEST = 'SAVE_EX_REQUEST';
// export const SAVE_EX_SUCCESS = 'SAVE_EX_SUCCESS';
// export const SAVE_EX_FAILURE = 'SAVE_EX_FAILURE'; 


export const SAVE_EX_REQUEST = 'SAVE_EX_REQUEST';
export const FETCH_EX_REQUEST = 'FETCH_EX_REQUEST';
export const UPDATE_EX_REQUEST = 'UPDATE_EX_REQUEST';
export const DELETE_EX_REQUEST = 'DELETE_EX_REQUEST';
export const EX_SUCCESS = 'EX_SUCCESS';
export const EX_FAILURE = 'EX_FAILURE';